### ISSUE TITLE
Print css 

### ISSUE THREAD

**Issue by xu3cl40122** [Lidemy/mentor-program-xu3cl40122#69]
## Print css 
``` css
 @media print {
   // 列印時的樣式
   page-break-before: always
   page-break-inside: avoid
}
 ```
* `page-break-before` 在 parent `display: flex` 時不作用
