### ISSUE TITLE
排版相關

### ISSUE THREAD

**Issue by xu3cl40122** [Lidemy/mentor-program-xu3cl40122#7]
## flexbox
* 當`flex-direction`為`column`，`justify-content`變成控制垂直向

* `flex-direction`和`flex-wrap`可以整合成`flex-flow`
ex:`flex-flow : column wrap;`

**Comment by xu3cl40122** [comment]
### z index 
z-index只能影響position值不是static的元素。
沒有定義z-index的值時，元素按照它們出現在DOM中的順序堆疊（層級越低，出現位置越靠上）。非靜態定位的元素（及其子元素）將始終覆蓋靜態定位（static）的元素，而不管HTML層次結構如何。

### background 預設為透明
所以即使 z index 較高的 div ，如果沒有設置 background 也可能顯示出本來應該在後面的顏色。
### 創造 container
```css
body,html 
    height 100%//把 body,html 設置 height， 即可用 height 100% 繼承 body 的高度
```
### 客製 input file button 
* 用 label 包起來，因為當 label 包在 input 外，點 label 就等於點到 input (也適用 checkbox 、radio)，把input file 設 display none ，然後自己刻一個。
* label 的 z-index 必須高於裡面的 div 才會先點到 label
* 有些瀏覽器好像不支援 display none 的 input ，可以用 position 把它藏起來，
``` CSS
<label class="">
       <input type="file" class="displayNone">
       <div class="addTodo_body_col_uploadButton">+</div>
</label>
```

**Comment by xu3cl40122** [comment]
## transition to 未知的 height or width
* 設置 max-height  hover  後把 max-height 變超大，讓他自己去適應其大小
```css
#menu #list {
    max-height: 0;
    transition: max-height 0.15s ease-out;
    overflow: hidden;
    background: #d5d5d5;
}

#menu:hover #list {
    max-height: 500px;
    transition: max-height 0.25s ease-in;
}
<div id="menu">
    <a>hover me</a>
    <ul id="list">
        <!-- Create a bunch, or not a bunch, of li's to see the timing. -->
        <li>item</li>
        <li>item</li>
        <li>item</li>
        <li>item</li>
        <li>item</li>
    </ul>
</div>
```
